spring.application.name=BaoziStore

# Porta do Servidor
server.port=8080

# Configuração do H2 Database em Memória
spring.datasource.url=jdbc:h2:mem:baozidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar H2 Console Web (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração do Spring Data JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
